languageCode = "en-us"
title = "BG Console"
baseURL = "/"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "docs"


[[menu.main]]
    name = "Get started"
    url = "/get-started/"
    weight = 1


[[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 2